// Generated by pkl-gen-ts
// Do not edit this file manually

export interface config {
  appName: string;
  version: string;
  server: Server;
  database: Database;
  features: Features;
  api: Api;
  ui: Ui;
}

export interface Server {
  host: string;
  port: number;
  ssl: boolean;
}

export interface Database {
  uri: string;
  maxConnections: number;
  timeout: number;
}

export interface Features {
  auth: boolean;
  logging: boolean;
  metrics: boolean;
  cache: boolean;
}

export interface Api {
  baseUrl: string;
  timeout: number;
  retries: number;
}

export interface Ui {
  theme: string;
  language: string;
  showDebugInfo: boolean;
}
