name: Publish All PKL Packages

on:
  push:
    tags:
      - "v*"

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - name: "pkl-cli"
            directory: "packages/pkl-cli"
          - name: "pkl-eval" 
            directory: "packages/pkl-eval"
          - name: "pkl-gen-ts"
            directory: "packages/pkl-gen-ts"
          - name: "pkl-webpack-loader"
            directory: "packages/pkl-webpack-loader"
          - name: "nextjs-pkl-plugin"
            directory: "packages/nextjs-pkl-plugin"
          - name: "pkl"
            directory: "packages/pkl"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org/"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Configure npm authentication
        run: |
          echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > ~/.npmrc
          echo "registry=https://registry.npmjs.org/" >> ~/.npmrc
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Extract version from tag
        id: extract_version
        run: |
          TAG_NAME=$(basename "$GITHUB_REF_NAME")
          VERSION=${TAG_NAME#v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Update package.json version
        working-directory: ./${{ matrix.package.directory }}
        run: pnpm version ${{ steps.extract_version.outputs.version }} --no-git-tag-version
        
      - name: Publish to NPM
        working-directory: ./${{ matrix.package.directory }}
        run: pnpm publish --no-git-checks --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}