name: Publish @nexo-labs/vite-pkl-plugin

on:
  push:
    tags:
      - "vite-pkl-plugin-v*"
    paths:
      - "packages/vite-pkl-plugin/**"

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org/"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Configure npm authentication
        run: |
          echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > ~/.npmrc
          echo "registry=https://registry.npmjs.org/" >> ~/.npmrc
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Extract version from tag
        id: extract_version
        run: |
          TAG_NAME=$(basename "$GITHUB_REF_NAME")
          VERSION=${TAG_NAME#vite-pkl-plugin-v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Update package version and dependencies
        working-directory: ./packages/vite-pkl-plugin
        run: |
          TARGET_VERSION="${{ steps.extract_version.outputs.version }}"
          echo "Setting version to: $TARGET_VERSION"
          
          # Update main version
          npm version $TARGET_VERSION --no-git-tag-version --allow-same-version
          
          # Update internal dependencies to use the same version
          node -e "
            const fs = require('fs');
            const pkg = JSON.parse(fs.readFileSync('package.json', 'utf8'));
            const version = '$TARGET_VERSION';
            
            // Update dependencies that are internal packages
            if (pkg.dependencies) {
              Object.keys(pkg.dependencies).forEach(dep => {
                if (dep.startsWith('@nexo-labs/')) {
                  pkg.dependencies[dep] = '^' + version;
                }
              });
            }
            
            fs.writeFileSync('package.json', JSON.stringify(pkg, null, 2) + '\\n');
          "
        
      - name: Publish to NPM
        working-directory: ./packages/vite-pkl-plugin
        run: pnpm publish --no-git-checks --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} 